=== 2. CONGRESSIONAL DISTRICT CAUCUS

2.1 At State Convention.::

2.1.1 Time and Place.::: At the beginning of each State Convention, at a time and place to be designated
by the State Chair, the State Convention delegates from each Congressional District shall hold a State
Convention Congressional District Caucus.

2.1.2 Certification of Delegates Entitled to Vote.::: Preceding the convening of each State convention
Congressional District Caucus, the Secretary of the State Central Committee shall certify to the District
Chair the names of all delegates and alternates entitled to representation at such Congressional District
Caucus. The list, so certified to the District Chair shall determine the persons entitled to vote on any
question which may come before such caucus. Vacancies shall be filled pursuant to Rule 1.1.13 herein.

2.1.3 Credentials How Settled.::: Any dispute concerning the credentials of delegates selected to attend
any State Convention Congressional District Caucus shall be determined by the Chair, First Associate
Chair and Second Associate Chair of the State Central Committee whose certificate resolving such
dispute shall be final so far as the membership to any Congressional District Caucus is concerned.

2.1.4 Nomination for Presidential Elector.::: At each State Convention Congressional District Caucus
in the presidential election years, the Caucus shall select one person properly affiliated with the
Democratic Party and legally eligible to serve for nomination by the State Convention to represent such
district as a Presidential Elector in the Electoral College. The Caucus shall recommend one person
properly affiliated with the Democratic Party and legally eligible to serve for nomination by the State
Convention to represent the State At-large as a Presidential Elector in the Electoral College. The District
Chair of said caucus shall certify such recommendations to the Chair of the Convention Committee to
Recommend Nominations of Presidential and Vice Presidential Electors.

2.1.5 Selection of State Convention Committee Members.::: Each State Convention Congressional
District Caucus shall select the persons who shall be recommended to the Convention to serve as
members of the various Convention committees as provided for in Rule 1.3 of these Bylaws.

2.2 At State Central Committee.::

2.2.1 Time and Place.::: A Congressional District Caucus shall be held in conjunction with each
meeting of the SCC.

2.2.2 Members Entitled to Vote.::: Preceding the convening of a Congressional District Caucus, the
Secretary of the SCC may certify to the District Chair the names of all members and alternates of the
State Central Committee residing in the district entitled to representation at such Congressional District
Caucus. The list so certified to the District Chair shall determine the persons entitled to vote on any
question which may come before such caucus.

2.3 At Other Times.::
A Congressional District Caucus may be held at a time and place to be designated by the Congressional
District Chair or at least six (6) congressional delegates qualified as defined in these Bylaws.

2.4 Congressional District Caucus Procedures.::

2.4.1 Voting.::: Each Caucus member who is found to be duly qualified to vote at any Congressional
District Caucus shall be entitled to one vote on any question coming before such caucus. No Caucus
Member shall be permitted to vote by proxy. No delegation shall apply the Unit Rule.

2.4.2 Resolutions.::: If a Congressional District Caucus wishes to adopt resolutions for presentation to the
State Central Committee or the State Convention, it may do so.

2.4.3 Quorum.::: A quorum shall consist of 25 percent of the membership.

2.4.4 State Rules of Order Govern.::: In the absence of any Rule governing a situation in a
Congressional District Caucus, the Rules of Order then in force as set out in Bylaw Section 1.4 or Bylaw
Section 8, as applicable, shall govern the procedure of any Congressional District Caucus.

