=== 7. PARTY RESOURCES

7.1 Defined.:: Party resources are those materials, physical or intellectual, that are produced by the
State Democratic Party or on its behalf or at its request and which are funded by the State Democratic
Party. Party resources also include staff members hired by the State Democratic Party.

7.2 Use.:: Party Resources are to be used to promote the success of the Democratic Party. Party
Resources are not an entitlement to any candidate or recognized affiliated caucus organization. The
allocation of party resources is at the discretion of the State Chair or the Chair’s designee and subject to
review by the State Executive Committee or the State Central Committee as circumstances warrant

7.3 Withholding Resources.:: Under extraordinary circumstances State Party resources may be
withheld from a candidate who is a registered Democrat or a recognized affiliated caucus organization.
These circumstances may include, but shall not be limited to, a candidate whose opponent is an
incumbent Democrat, a person who has not been an active Democrat, a candidate whose campaign
organization is dominated by and supported by other political parties, a candidate who has failed to report
his or her financial status to the Federal Election Commission or the Nebraska Accountability and
Disclosure Commission, and a recognized affiliated caucus organization that compromises the goals,
strategy, policy, or integrity of the Nebraska Democratic Party.

