=== 6. ELIGIBILITY FOR BALLOT

6.1:: It is contrary to the policy of the Nebraska Democratic Party for the name of any person to be
placed upon the primary ballot of the Democratic Party as a candidate for nomination, election, or
preferential vote in any state or county primary election if such a person is not affiliated with the
Democratic Party. Further the name of no such person should be placed upon the primary ballot of the
Democratic Party as a candidate for nomination, election or preferential vote in any state or county
primary election if such person has announced his/her intention of being a candidate for public office on
the ticket of any other than the Democratic Party concurrently with being a candidate for public office on
the ticket of the Democratic Party.

6.2:: In the absence of any statute specifically denying the right of the Nebraska Democratic Party to
determine the names of those who may be or may not be placed by the Secretary of the State or a proper
County official on the Democratic primary ballot at any primary election held within the State of
Nebraska
(a)::: no person shall be permitted to file or be filed on a primary election ballot of the Democratic
Party as a candidate for nomination, election, or preferential vote, in a state or county primary election
who is not affiliated with the Democratic Party, and
(b)::: no person shall be permitted to file or be filed on
a primary ballot of the Democratic Party as a candidate for nomination, election, or preferential vote who
has announced his/her intention to be a candidate for public office on the ticket of any political party other
than the Democratic Party concurrently with being a candidate for public office on the ticket of the
Democratic Party.

