=== 4. DEMOCRATIC NATIONAL COMMITTEE

4.1 Election of National Committeeman and National Committeewoman.:: During presidential
election years, convention delegates shall elect two (2) members of the Democratic National Committee
from Nebraska, a National Committeeman and a National Committeewoman, who shall serve for a term
of four (4) years each and until their successors are elected and qualified. Said four-year term shall begin
after the Democratic National Convention.

4.2 State Chair and First Associate Chair.:: In accordance with the Bylaws of the Democratic
National Committee, the Chair and 1st Associate Chair of the Nebraska Democratic Party shall serve as
members of the Democratic National Committee for terms concurrent with their terms as State Party
officers.

4.3 Other Elected or Appointed Members.:: Additional elected members of the Democratic
National committee are allocated on the basis of population and the Democratic vote for President as
stipulated in the Charter and Bylaws of the Democratic Party of the United States. Should an additional
member be allocated to Nebraska, the State 2nd Associate Chair would fill that position. The Democratic
National Committee has authority, as proscribed in its Charter and Bylaws, to appoint additional members
to that body. Such appointed members serve terms as stipulated by the DNC when appointed, but not
longer than beyond the day the next National Convention adjourns.

4.4 Vacancies.:: Any vacancy in such membership of the Democratic National Committee from
Nebraska shall be filled for the unexpired term by the Democratic State Central Committee.

4.5 Certification of Elections.:: Following any election of such a National Committeeman or
National Committeewoman from Nebraska, or State Chair and First Associate Chair, the Chair and
Secretary of the Democratic State Central Committee shall forthwith certify the election of such person or
persons to the Secretary of the Democratic National Committee.

