=== ARTICLE V - VACANCIES

When a vacancy occurs, it shall be filled at the following State Central Committee meeting in the
following manner:

A. State Chair, Associate Chairs, or National Committee Representatives shall be replaced by
election by the State Central Committee as directed in the Bylaws of the Nebraska Democratic Party.

B. Central Committee vacancies of delegates and alternates shall be filled through nomination by
the appropriate Congressional District Caucus with election by the State Central Committee.

C. Executive Committee vacancies of members who are appointed by the State Chair shall be filled
through nomination by the State Chair with confirmation by the State Central Committee.

D. Congressional District Chairs or Associate Chairs shall be replaced by election in their respective
district caucuses of the State Central Committee following notification of the vacancy.

E. Vacancies in County Party offices shall be filled through election by the respective County
Central Committee or, when a county central committee is not present, by the State Chair.

